# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160913_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
